services:
  covid-back:
    build:
      context: ./covid
    ports:
      - "8080:8080"
    container_name: covid-back
    networks:
      - observatorio-network

  covid-front:
    build:
      context: ./covidfront
    ports:
      - "5173:80"
    container_name: covid-front
    networks:
      - observatorio-network

  dengue:
    build:
      context: ./dengue
    ports:
      - "8081:8081"
    container_name: dengue-api
    networks:
      - observatorio-network

#  dengue-front:
#    build:
#      context: ./denguefront
#    ports:
#      - "5174:81"
#    container_name: dengue-front
#    networks:
#     - observatorio-network

networks:
  observatorio-network:
    driver: bridge
