version: "3.9"
services:
  covid-back:
    build:
      context: ./covid
    ports:
      - "8080:8080"
    container_name: covid-back
    networks:
      - observatorio-network

  covid-front:
    build:
      context: ./covidfront
    ports:
      - "5173:80"
    container_name: covid-front
    networks:
      - observatorio-network

#  dengue:
#    build:
#      context: ./dengue
#    ports:
#      - "5000:5000"
#    container_name: dengue-api
#    networks:
#      - observatorio-network

networks:
  observatorio-network:
    driver: bridge
